// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/call/:scenarioId": {
    params: {
      "scenarioId": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/integrated-ai/stream": {
    params: {};
  };
  "/hcgi/platform/*": {
    params: {
      "*": string;
    };
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/call/:scenarioId" | "/sitemap.xml" | "/robots.txt" | "/api/health" | "/api/integrated-ai/stream" | "/hcgi/platform/*" | "/api/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/call.$scenarioId.tsx": {
    id: "routes/call.$scenarioId";
    page: "/call/:scenarioId";
  };
  "routes/sitemap.xml.ts": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.integrated-ai.stream.ts": {
    id: "routes/api.integrated-ai.stream";
    page: "/api/integrated-ai/stream";
  };
  "routes/hcgi.platform.$.ts": {
    id: "routes/hcgi.platform.$";
    page: "/hcgi/platform/*";
  };
  "routes/api.$.ts": {
    id: "routes/api.$";
    page: "/api/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/auth": typeof import("./src/routes/auth.tsx");
  "routes/call.$scenarioId": typeof import("./src/routes/call.$scenarioId.tsx");
  "routes/sitemap.xml": typeof import("./src/routes/sitemap.xml.ts");
  "routes/robots.txt": typeof import("./src/routes/robots.txt.ts");
  "routes/api.health": typeof import("./src/routes/api.health.ts");
  "routes/api.integrated-ai.stream": typeof import("./src/routes/api.integrated-ai.stream.ts");
  "routes/hcgi.platform.$": typeof import("./src/routes/hcgi.platform.$.ts");
  "routes/api.$": typeof import("./src/routes/api.$.ts");
};